'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls

Namespace RibbonLib.Controls
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdListRecentItems As UInteger = 22
            Public Const cmdButtonRun As UInteger = 21
            Public Const cmdButtonOpenVirtualCellPackFile As UInteger = 3
            Public Const cmdButtonExit As UInteger = 4
            Public Const cmdMenuVirtualCellViewer As UInteger = 2
            Public Const cmdTabVirtualCellBrowser As UInteger = 5
            Public Const cmdGroupVirtualCellBrowser As UInteger = 7
            Public Const cmdButtonCloseVirtualCellPackFile As UInteger = 18
            Public Const cmdButtonResetNetworkTable As UInteger = 9
            Public Const cmdGroupDataBrowser As UInteger = 16
            Public Const cmdButtonViewMassActivityLoads As UInteger = 10
            Public Const cmdButtonExportMoleculeExpression As UInteger = 11
            Public Const cmdButtonExportFluxomics As UInteger = 12
            Public Const cmdGroupBrowserToolkit As UInteger = 17
            Public Const cmdButtonPhenotypeAnalysis As UInteger = 13
            Public Const cmdTabDataViewer As UInteger = 6
            Public Const cmdGroupDataViewer As UInteger = 8
            Public Const cmdButtonExportPlotMatrix As UInteger = 14
            Public Const cmdCheckPlotLogScale As UInteger = 15
            Public Const cmdMenuWorkbench As UInteger = 19
            Public Const cmdTabWorkbench As UInteger = 20
            Public Const cmdButtonInspectCellModel As UInteger = 27
            Public Const cmdGroupTools As UInteger = 23
            Public Const cmdButtonEditCultureMedium As UInteger = 24
            Public Const cmdButtonEditMutation As UInteger = 28
            Public Const cmdGroupModelling As UInteger = 25
            Public Const cmdButtonIDAnnotation As UInteger = 26
        End Class

        ' ContextPopup CommandName

        Private _ribbon As Ribbon
        Public ReadOnly Property Ribbon As Ribbon
            Get
                Return _ribbon
            End Get
        End Property
        Private _ListRecentItems As RibbonRecentItems
        ''' <summary>
        ''' Recent Items
        ''' </summary>
        Public ReadOnly Property ListRecentItems As RibbonRecentItems
            Get
                Return _ListRecentItems
            End Get
        End Property
        Private _ButtonRun As RibbonButton
        ''' <summary>
        ''' Run
        ''' </summary>
        Public ReadOnly Property ButtonRun As RibbonButton
            Get
                Return _ButtonRun
            End Get
        End Property
        Private _ButtonOpenVirtualCellPackFile As RibbonButton
        ''' <summary>
        ''' Open VirtualCell Pack File
        ''' </summary>
        Public ReadOnly Property ButtonOpenVirtualCellPackFile As RibbonButton
            Get
                Return _ButtonOpenVirtualCellPackFile
            End Get
        End Property
        Private _ButtonExit As RibbonButton
        ''' <summary>
        ''' Exit
        ''' </summary>
        Public ReadOnly Property ButtonExit As RibbonButton
            Get
                Return _ButtonExit
            End Get
        End Property
        Private _MenuVirtualCellViewer As RibbonTabGroup
        ''' <summary>
        ''' VirtualCell Viewer
        ''' </summary>
        Public ReadOnly Property MenuVirtualCellViewer As RibbonTabGroup
            Get
                Return _MenuVirtualCellViewer
            End Get
        End Property
        Private _TabVirtualCellBrowser As RibbonTab
        Public ReadOnly Property TabVirtualCellBrowser As RibbonTab
            Get
                Return _TabVirtualCellBrowser
            End Get
        End Property
        Private _GroupVirtualCellBrowser As RibbonGroup
        ''' <summary>
        ''' Virtual Cell Browser
        ''' </summary>
        Public ReadOnly Property GroupVirtualCellBrowser As RibbonGroup
            Get
                Return _GroupVirtualCellBrowser
            End Get
        End Property
        Private _ButtonCloseVirtualCellPackFile As RibbonButton
        Public ReadOnly Property ButtonCloseVirtualCellPackFile As RibbonButton
            Get
                Return _ButtonCloseVirtualCellPackFile
            End Get
        End Property
        Private _ButtonResetNetworkTable As RibbonButton
        ''' <summary>
        ''' Reset Network Table
        ''' </summary>
        Public ReadOnly Property ButtonResetNetworkTable As RibbonButton
            Get
                Return _ButtonResetNetworkTable
            End Get
        End Property
        Private _GroupDataBrowser As RibbonGroup
        Public ReadOnly Property GroupDataBrowser As RibbonGroup
            Get
                Return _GroupDataBrowser
            End Get
        End Property
        Private _ButtonViewMassActivityLoads As RibbonButton
        ''' <summary>
        ''' View Mass Activity Loads
        ''' </summary>
        Public ReadOnly Property ButtonViewMassActivityLoads As RibbonButton
            Get
                Return _ButtonViewMassActivityLoads
            End Get
        End Property
        Private _ButtonExportMoleculeExpression As RibbonButton
        Public ReadOnly Property ButtonExportMoleculeExpression As RibbonButton
            Get
                Return _ButtonExportMoleculeExpression
            End Get
        End Property
        Private _ButtonExportFluxomics As RibbonButton
        ''' <summary>
        ''' Export Fluxomics
        ''' </summary>
        Public ReadOnly Property ButtonExportFluxomics As RibbonButton
            Get
                Return _ButtonExportFluxomics
            End Get
        End Property
        Private _GroupBrowserToolkit As RibbonGroup
        Public ReadOnly Property GroupBrowserToolkit As RibbonGroup
            Get
                Return _GroupBrowserToolkit
            End Get
        End Property
        Private _ButtonPhenotypeAnalysis As RibbonButton
        ''' <summary>
        ''' Phenotype Analysis
        ''' </summary>
        Public ReadOnly Property ButtonPhenotypeAnalysis As RibbonButton
            Get
                Return _ButtonPhenotypeAnalysis
            End Get
        End Property
        Private _TabDataViewer As RibbonTab
        Public ReadOnly Property TabDataViewer As RibbonTab
            Get
                Return _TabDataViewer
            End Get
        End Property
        Private _GroupDataViewer As RibbonGroup
        ''' <summary>
        ''' Data Viewer
        ''' </summary>
        Public ReadOnly Property GroupDataViewer As RibbonGroup
            Get
                Return _GroupDataViewer
            End Get
        End Property
        Private _ButtonExportPlotMatrix As RibbonButton
        ''' <summary>
        ''' Export Plot Matrix
        ''' </summary>
        Public ReadOnly Property ButtonExportPlotMatrix As RibbonButton
            Get
                Return _ButtonExportPlotMatrix
            End Get
        End Property
        Private _CheckPlotLogScale As RibbonCheckBox
        ''' <summary>
        ''' Log Scale
        ''' </summary>
        Public ReadOnly Property CheckPlotLogScale As RibbonCheckBox
            Get
                Return _CheckPlotLogScale
            End Get
        End Property
        Private _MenuWorkbench As RibbonTab
        ''' <summary>
        ''' Workbench
        ''' </summary>
        Public ReadOnly Property MenuWorkbench As RibbonTab
            Get
                Return _MenuWorkbench
            End Get
        End Property
        Private _TabWorkbench As RibbonGroup
        ''' <summary>
        ''' Workbench
        ''' </summary>
        Public ReadOnly Property TabWorkbench As RibbonGroup
            Get
                Return _TabWorkbench
            End Get
        End Property
        Private _ButtonInspectCellModel As RibbonButton
        ''' <summary>
        ''' Inspect the virtual cell network model
        ''' </summary>
        Public ReadOnly Property ButtonInspectCellModel As RibbonButton
            Get
                Return _ButtonInspectCellModel
            End Get
        End Property
        Private _GroupTools As RibbonGroup
        ''' <summary>
        ''' Tools
        ''' </summary>
        Public ReadOnly Property GroupTools As RibbonGroup
            Get
                Return _GroupTools
            End Get
        End Property
        Private _ButtonEditCultureMedium As RibbonButton
        ''' <summary>
        ''' Edit the preset profile of the culture medium.
        ''' </summary>
        Public ReadOnly Property ButtonEditCultureMedium As RibbonButton
            Get
                Return _ButtonEditCultureMedium
            End Get
        End Property
        Private _ButtonEditMutation As RibbonButton
        ''' <summary>
        ''' Mutation Tool
        ''' </summary>
        Public ReadOnly Property ButtonEditMutation As RibbonButton
            Get
                Return _ButtonEditMutation
            End Get
        End Property
        Private _GroupModelling As RibbonGroup
        ''' <summary>
        ''' Virtual cell modelling
        ''' </summary>
        Public ReadOnly Property GroupModelling As RibbonGroup
            Get
                Return _GroupModelling
            End Get
        End Property
        Private _ButtonIDAnnotation As RibbonButton
        ''' <summary>
        ''' Make cell component id annotation via blastp alignment with the local database.
        ''' </summary>
        Public ReadOnly Property ButtonIDAnnotation As RibbonButton
            Get
                Return _ButtonIDAnnotation
            End Get
        End Property

        Public Sub New(ByVal ribbon As Ribbon)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _ListRecentItems = New RibbonRecentItems(_ribbon, Cmd.cmdListRecentItems)
            _ButtonRun = New RibbonButton(_ribbon, Cmd.cmdButtonRun)
            _ButtonOpenVirtualCellPackFile = New RibbonButton(_ribbon, Cmd.cmdButtonOpenVirtualCellPackFile)
            _ButtonExit = New RibbonButton(_ribbon, Cmd.cmdButtonExit)
            _MenuVirtualCellViewer = New RibbonTabGroup(_ribbon, Cmd.cmdMenuVirtualCellViewer)
            _TabVirtualCellBrowser = New RibbonTab(_ribbon, Cmd.cmdTabVirtualCellBrowser)
            _GroupVirtualCellBrowser = New RibbonGroup(_ribbon, Cmd.cmdGroupVirtualCellBrowser)
            _ButtonCloseVirtualCellPackFile = New RibbonButton(_ribbon, Cmd.cmdButtonCloseVirtualCellPackFile)
            _ButtonResetNetworkTable = New RibbonButton(_ribbon, Cmd.cmdButtonResetNetworkTable)
            _GroupDataBrowser = New RibbonGroup(_ribbon, Cmd.cmdGroupDataBrowser)
            _ButtonViewMassActivityLoads = New RibbonButton(_ribbon, Cmd.cmdButtonViewMassActivityLoads)
            _ButtonExportMoleculeExpression = New RibbonButton(_ribbon, Cmd.cmdButtonExportMoleculeExpression)
            _ButtonExportFluxomics = New RibbonButton(_ribbon, Cmd.cmdButtonExportFluxomics)
            _GroupBrowserToolkit = New RibbonGroup(_ribbon, Cmd.cmdGroupBrowserToolkit)
            _ButtonPhenotypeAnalysis = New RibbonButton(_ribbon, Cmd.cmdButtonPhenotypeAnalysis)
            _TabDataViewer = New RibbonTab(_ribbon, Cmd.cmdTabDataViewer)
            _GroupDataViewer = New RibbonGroup(_ribbon, Cmd.cmdGroupDataViewer)
            _ButtonExportPlotMatrix = New RibbonButton(_ribbon, Cmd.cmdButtonExportPlotMatrix)
            _CheckPlotLogScale = New RibbonCheckBox(_ribbon, Cmd.cmdCheckPlotLogScale)
            _MenuWorkbench = New RibbonTab(_ribbon, Cmd.cmdMenuWorkbench)
            _TabWorkbench = New RibbonGroup(_ribbon, Cmd.cmdTabWorkbench)
            _ButtonInspectCellModel = New RibbonButton(_ribbon, Cmd.cmdButtonInspectCellModel)
            _GroupTools = New RibbonGroup(_ribbon, Cmd.cmdGroupTools)
            _ButtonEditCultureMedium = New RibbonButton(_ribbon, Cmd.cmdButtonEditCultureMedium)
            _ButtonEditMutation = New RibbonButton(_ribbon, Cmd.cmdButtonEditMutation)
            _GroupModelling = New RibbonGroup(_ribbon, Cmd.cmdGroupModelling)
            _ButtonIDAnnotation = New RibbonButton(_ribbon, Cmd.cmdButtonIDAnnotation)
        End Sub

    End Class
End Namespace
