//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdListRecentItems = 22;
            public const uint cmdButtonRun = 21;
            public const uint cmdButtonOpenVirtualCellPackFile = 3;
            public const uint cmdButtonMenuLicense = 36;
            public const uint cmdMenuAbout = 34;
            public const uint cmdButtonExit = 4;
            public const uint cmdButtonSaveMenu = 30;
            public const uint cmdButtonOpenMenu = 29;
            public const uint cmdMenuVirtualCellViewer = 2;
            public const uint cmdTabVirtualCellBrowser = 5;
            public const uint cmdGroupVirtualCellBrowser = 7;
            public const uint cmdButtonCloseVirtualCellPackFile = 18;
            public const uint cmdButtonResetNetworkTable = 9;
            public const uint cmdGroupDataBrowser = 16;
            public const uint cmdButtonViewMassActivityLoads = 10;
            public const uint cmdButtonExportMoleculeExpression = 11;
            public const uint cmdButtonExportFluxomics = 12;
            public const uint cmdGroupBrowserToolkit = 17;
            public const uint cmdButtonPhenotypeAnalysis = 13;
            public const uint cmdTabDataViewer = 6;
            public const uint cmdGroupDataViewer = 8;
            public const uint cmdButtonExportPlotMatrix = 14;
            public const uint cmdCheckPlotLogScale = 15;
            public const uint cmdMenuWorkbench = 19;
            public const uint cmdTabWorkbench = 20;
            public const uint cmdTabVirtualCellTool = 33;
            public const uint cmdButtonInspectCellModel = 27;
            public const uint cmdGroupTools = 23;
            public const uint cmdButtonEditMutation = 28;
            public const uint cmdButtonEditCultureMedium = 24;
            public const uint cmdGroupModelling = 25;
            public const uint cmdButtonIDAnnotation = 26;
            public const uint cmdGroupMainMenu = 31;
            public const uint cmdTabMainMenu = 32;
            public const uint cmdGroupOthers = 35;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        /// <summary>
        /// Recent Items
        /// </summary>
        public RibbonRecentItems ListRecentItems { get; private set; }
        /// <summary>
        /// Run
        /// </summary>
        public RibbonButton ButtonRun { get; private set; }
        /// <summary>
        /// Open VirtualCell Pack File
        /// </summary>
        public RibbonButton ButtonOpenVirtualCellPackFile { get; private set; }
        public RibbonButton ButtonMenuLicense { get; private set; }
        public RibbonButton MenuAbout { get; private set; }
        /// <summary>
        /// Exit
        /// </summary>
        public RibbonButton ButtonExit { get; private set; }
        public RibbonButton ButtonSaveMenu { get; private set; }
        public RibbonButton ButtonOpenMenu { get; private set; }
        /// <summary>
        /// VirtualCell Viewer
        /// </summary>
        public RibbonTabGroup MenuVirtualCellViewer { get; private set; }
        public RibbonTab TabVirtualCellBrowser { get; private set; }
        /// <summary>
        /// Virtual Cell Browser
        /// </summary>
        public RibbonGroup GroupVirtualCellBrowser { get; private set; }
        public RibbonButton ButtonCloseVirtualCellPackFile { get; private set; }
        /// <summary>
        /// Reset Network Table
        /// </summary>
        public RibbonButton ButtonResetNetworkTable { get; private set; }
        public RibbonGroup GroupDataBrowser { get; private set; }
        /// <summary>
        /// View Mass Activity Loads
        /// </summary>
        public RibbonButton ButtonViewMassActivityLoads { get; private set; }
        public RibbonButton ButtonExportMoleculeExpression { get; private set; }
        /// <summary>
        /// Export Fluxomics
        /// </summary>
        public RibbonButton ButtonExportFluxomics { get; private set; }
        public RibbonGroup GroupBrowserToolkit { get; private set; }
        /// <summary>
        /// Phenotype Analysis
        /// </summary>
        public RibbonButton ButtonPhenotypeAnalysis { get; private set; }
        public RibbonTab TabDataViewer { get; private set; }
        /// <summary>
        /// Data Viewer
        /// </summary>
        public RibbonGroup GroupDataViewer { get; private set; }
        /// <summary>
        /// Export Plot Matrix
        /// </summary>
        public RibbonButton ButtonExportPlotMatrix { get; private set; }
        /// <summary>
        /// Log Scale
        /// </summary>
        public RibbonCheckBox CheckPlotLogScale { get; private set; }
        /// <summary>
        /// Virtual Cell
        /// </summary>
        public RibbonTabGroup MenuWorkbench { get; private set; }
        /// <summary>
        /// Virtual Cell
        /// </summary>
        public RibbonTab TabWorkbench { get; private set; }
        public RibbonGroup TabVirtualCellTool { get; private set; }
        /// <summary>
        /// Inspect the virtual cell network model
        /// </summary>
        public RibbonButton ButtonInspectCellModel { get; private set; }
        /// <summary>
        /// Tools
        /// </summary>
        public RibbonGroup GroupTools { get; private set; }
        /// <summary>
        /// Mutation Tool
        /// </summary>
        public RibbonButton ButtonEditMutation { get; private set; }
        /// <summary>
        /// Edit the preset profile of the culture medium.
        /// </summary>
        public RibbonButton ButtonEditCultureMedium { get; private set; }
        /// <summary>
        /// Virtual cell modelling
        /// </summary>
        public RibbonGroup GroupModelling { get; private set; }
        /// <summary>
        /// Make cell component id annotation via blastp alignment with the local database.
        /// </summary>
        public RibbonButton ButtonIDAnnotation { get; private set; }
        public RibbonTab GroupMainMenu { get; private set; }
        public RibbonGroup TabMainMenu { get; private set; }
        public RibbonGroup GroupOthers { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            ListRecentItems = new RibbonRecentItems(ribbon, Cmd.cmdListRecentItems);
            ButtonRun = new RibbonButton(ribbon, Cmd.cmdButtonRun);
            ButtonOpenVirtualCellPackFile = new RibbonButton(ribbon, Cmd.cmdButtonOpenVirtualCellPackFile);
            ButtonMenuLicense = new RibbonButton(ribbon, Cmd.cmdButtonMenuLicense);
            MenuAbout = new RibbonButton(ribbon, Cmd.cmdMenuAbout);
            ButtonExit = new RibbonButton(ribbon, Cmd.cmdButtonExit);
            ButtonSaveMenu = new RibbonButton(ribbon, Cmd.cmdButtonSaveMenu);
            ButtonOpenMenu = new RibbonButton(ribbon, Cmd.cmdButtonOpenMenu);
            MenuVirtualCellViewer = new RibbonTabGroup(ribbon, Cmd.cmdMenuVirtualCellViewer);
            TabVirtualCellBrowser = new RibbonTab(ribbon, Cmd.cmdTabVirtualCellBrowser);
            GroupVirtualCellBrowser = new RibbonGroup(ribbon, Cmd.cmdGroupVirtualCellBrowser);
            ButtonCloseVirtualCellPackFile = new RibbonButton(ribbon, Cmd.cmdButtonCloseVirtualCellPackFile);
            ButtonResetNetworkTable = new RibbonButton(ribbon, Cmd.cmdButtonResetNetworkTable);
            GroupDataBrowser = new RibbonGroup(ribbon, Cmd.cmdGroupDataBrowser);
            ButtonViewMassActivityLoads = new RibbonButton(ribbon, Cmd.cmdButtonViewMassActivityLoads);
            ButtonExportMoleculeExpression = new RibbonButton(ribbon, Cmd.cmdButtonExportMoleculeExpression);
            ButtonExportFluxomics = new RibbonButton(ribbon, Cmd.cmdButtonExportFluxomics);
            GroupBrowserToolkit = new RibbonGroup(ribbon, Cmd.cmdGroupBrowserToolkit);
            ButtonPhenotypeAnalysis = new RibbonButton(ribbon, Cmd.cmdButtonPhenotypeAnalysis);
            TabDataViewer = new RibbonTab(ribbon, Cmd.cmdTabDataViewer);
            GroupDataViewer = new RibbonGroup(ribbon, Cmd.cmdGroupDataViewer);
            ButtonExportPlotMatrix = new RibbonButton(ribbon, Cmd.cmdButtonExportPlotMatrix);
            CheckPlotLogScale = new RibbonCheckBox(ribbon, Cmd.cmdCheckPlotLogScale);
            MenuWorkbench = new RibbonTabGroup(ribbon, Cmd.cmdMenuWorkbench);
            TabWorkbench = new RibbonTab(ribbon, Cmd.cmdTabWorkbench);
            TabVirtualCellTool = new RibbonGroup(ribbon, Cmd.cmdTabVirtualCellTool);
            ButtonInspectCellModel = new RibbonButton(ribbon, Cmd.cmdButtonInspectCellModel);
            GroupTools = new RibbonGroup(ribbon, Cmd.cmdGroupTools);
            ButtonEditMutation = new RibbonButton(ribbon, Cmd.cmdButtonEditMutation);
            ButtonEditCultureMedium = new RibbonButton(ribbon, Cmd.cmdButtonEditCultureMedium);
            GroupModelling = new RibbonGroup(ribbon, Cmd.cmdGroupModelling);
            ButtonIDAnnotation = new RibbonButton(ribbon, Cmd.cmdButtonIDAnnotation);
            GroupMainMenu = new RibbonTab(ribbon, Cmd.cmdGroupMainMenu);
            TabMainMenu = new RibbonGroup(ribbon, Cmd.cmdTabMainMenu);
            GroupOthers = new RibbonGroup(ribbon, Cmd.cmdGroupOthers);
        }

    }
}
